export default{
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/1.jpg',
      price: 60,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/2.jpg',
      price: 50,
      brand: ' Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/3.jpg',
      price: 70,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/4.jpg',
      price: 180,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/5.jpg',
      price: 100,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/6.jpg',
      price: 90,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 0,
    },
    {
      _id: '7',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/8.jpg',
      price: 50,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 8,
    },
    {
      _id: '8',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/9.jpg',
      price: 140,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
    },
    {
      _id: '9',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/7.jpg',
      price: 220,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
    },
    {
      _id: '10',
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/10.jpg',
      price: 110,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
    },
  ]
}